### ISSUE TITLE
Virtual cluster will not show bad resource if enough nodes are guaranteed

### ISSUE THREAD

**Issue by debuggy** [microsoft/hivedscheduler#15]
There are 14 nodes and 3 virtual clusters total in pai int cluster:
```
Default: 10 nodes
Vc1: 2 nodes
Vc2: 2nodes
```
When I shut down 2 nodes in pai, the home page resource chart will not show the bad node status because there are enough idle nodes in pai for all vcs. 

![image](https://user-images.githubusercontent.com/8444268/81643311-eb5c9400-9457-11ea-8f02-ffec6caf0d78.png)

When I submited several jobs and then shut down another node, the cluster is too busy to manage enough idle nodes for vc, so the home page chart will show the bad node status.

![image](https://user-images.githubusercontent.com/8444268/81643333-f44d6580-9457-11ea-8cc3-95510de3da68.png)

**Comment by fanyangCS** [comment]
This is a by-design feature. HiveD's VC has a dynamic binding mechanism that binds a virtual node to an actual physical node only when necessary. So it hides the hardware failures when possible, and show the failures when they are inevitable.
