### ISSUE TITLE
Infinitely retry in intra-VC scheduler due to inconsistent view of bad cells.

### ISSUE THREAD

**Issue by hzhua** [microsoft/hivedscheduler#25]
If bad cells are not bound to VCs, it is possible that intra-VC scheduler keeps schedule a job to bad cells, which cannot find the healthy cell in the physical cluster. When the intra-VC scheduler is aware of the bad cells, it will avoid placing a job on the bad cells.

Example:
A physical cluster of two L2 cells, each of which can be split to two L1 cells. There is only one VC with the assignment of two L2 cells. 
Each of the physical L2 cell has one bad GPU (L1 cell).
If the intra-VC scheduler is unware of the bad GPUs, it can place two 1-GPU requests using a L2 cell, following a packing policy. (suppose it is a gang allocation)
However, there is no healthy L2 cell in the physical cluster. Buddy allocation returns an allocation failure. Due to the intra-VC scheduler cannot see bad cells in its VC, it may infinitely retry the same placement (two 1-GPU in a L2 cell).

It is necessary to pre-bind the bad cells to VCs that expose the bad GPUs to intra-VC schedulers.

**Comment by fanyangCS** [comment]
fixed in this PR: https://github.com/microsoft/hivedscheduler/pull/17
